<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-23T14:57:27 AST" name="Default suite" finished-at="2024-10-23T14:57:34 AST" duration-ms="7772">
    <groups>
    </groups>
    <test started-at="2024-10-23T14:57:27 AST" name="Default test" finished-at="2024-10-23T14:57:34 AST" duration-ms="7772">
      <class name="myTest">
        <test-method is-config="true" signature="mysetup()[pri:0, instance:myTest@340b9973]" started-at="2024-10-23T14:57:27 AST" name="mysetup" finished-at="2024-10-23T14:57:34 AST" duration-ms="7068" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mysetup -->
        <test-method signature="CheckTheEnglishLanguage()[pri:1, instance:myTest@340b9973]" started-at="2024-10-23T14:57:34 AST" name="CheckTheEnglishLanguage" finished-at="2024-10-23T14:57:34 AST" duration-ms="134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckTheEnglishLanguage -->
        <test-method signature="CheckCurrncy()[pri:2, instance:myTest@340b9973]" started-at="2024-10-23T14:57:34 AST" name="CheckCurrncy" finished-at="2024-10-23T14:57:34 AST" duration-ms="85" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckCurrncy -->
        <test-method signature="CheckNumber()[pri:3, instance:myTest@340b9973]" started-at="2024-10-23T14:57:34 AST" name="CheckNumber" finished-at="2024-10-23T14:57:34 AST" duration-ms="45" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckNumber -->
        <test-method signature="CheckQitafLogo()[pri:4, instance:myTest@340b9973]" started-at="2024-10-23T14:57:34 AST" name="CheckQitafLogo" finished-at="2024-10-23T14:57:34 AST" duration-ms="58" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckQitafLogo -->
        <test-method signature="CheckSearch()[pri:5, instance:myTest@340b9973]" started-at="2024-10-23T14:57:34 AST" name="CheckSearch" finished-at="2024-10-23T14:57:34 AST" duration-ms="290" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at myTest.CheckSearch(myTest.java:59)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckSearch -->
      </class> <!-- myTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
